
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Authentification", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Authentification {


    /**
     * 
     * @param password
     * @param email
     * @return
     *     returns service.User
     */
    @WebMethod(operationName = "Authentification")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Authentification", targetNamespace = "http://service/", className = "service.Authentification_Type")
    @ResponseWrapper(localName = "AuthentificationResponse", targetNamespace = "http://service/", className = "service.AuthentificationResponse")
    @Action(input = "http://service/Authentification/AuthentificationRequest", output = "http://service/Authentification/AuthentificationResponse")
    public User authentification(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "Password", targetNamespace = "")
        String password);
    
    

}
