
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthentificationService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/Authentification?wsdl")
public class AuthentificationService
    extends Service
{

    private final static URL AUTHENTIFICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHENTIFICATIONSERVICE_EXCEPTION;
    private final static QName AUTHENTIFICATIONSERVICE_QNAME = new QName("http://service/", "AuthentificationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Authentification?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHENTIFICATIONSERVICE_WSDL_LOCATION = url;
        AUTHENTIFICATIONSERVICE_EXCEPTION = e;
    }

    public AuthentificationService() {
        super(__getWsdlLocation(), AUTHENTIFICATIONSERVICE_QNAME);
    }

    public AuthentificationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTIFICATIONSERVICE_QNAME, features);
    }

    public AuthentificationService(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTIFICATIONSERVICE_QNAME);
    }

    public AuthentificationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTIFICATIONSERVICE_QNAME, features);
    }

    public AuthentificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthentificationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Authentification
     */
    @WebEndpoint(name = "AuthentificationPort")
    public Authentification getAuthentificationPort() {
        return super.getPort(new QName("http://service/", "AuthentificationPort"), Authentification.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Authentification
     */
    @WebEndpoint(name = "AuthentificationPort")
    public Authentification getAuthentificationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "AuthentificationPort"), Authentification.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTIFICATIONSERVICE_EXCEPTION!= null) {
            throw AUTHENTIFICATIONSERVICE_EXCEPTION;
        }
        return AUTHENTIFICATIONSERVICE_WSDL_LOCATION;
    }

}
