
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserManagementWS", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/UserManagement?wsdl")
public class UserManagementWS
    extends Service
{

    private final static URL USERMANAGEMENTWS_WSDL_LOCATION;
    private final static WebServiceException USERMANAGEMENTWS_EXCEPTION;
    private final static QName USERMANAGEMENTWS_QNAME = new QName("http://service/", "UserManagementWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/UserManagement?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERMANAGEMENTWS_WSDL_LOCATION = url;
        USERMANAGEMENTWS_EXCEPTION = e;
    }

    public UserManagementWS() {
        super(__getWsdlLocation(), USERMANAGEMENTWS_QNAME);
    }

    public UserManagementWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERMANAGEMENTWS_QNAME, features);
    }

    public UserManagementWS(URL wsdlLocation) {
        super(wsdlLocation, USERMANAGEMENTWS_QNAME);
    }

    public UserManagementWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERMANAGEMENTWS_QNAME, features);
    }

    public UserManagementWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserManagementWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserManagement
     */
    @WebEndpoint(name = "UserManagementPort")
    public UserManagement getUserManagementPort() {
        return super.getPort(new QName("http://service/", "UserManagementPort"), UserManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserManagement
     */
    @WebEndpoint(name = "UserManagementPort")
    public UserManagement getUserManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "UserManagementPort"), UserManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERMANAGEMENTWS_EXCEPTION!= null) {
            throw USERMANAGEMENTWS_EXCEPTION;
        }
        return USERMANAGEMENTWS_WSDL_LOCATION;
    }

}
