
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserManagement", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserManagement {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://service/", className = "service.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://service/", className = "service.AddUserResponse")
    @Action(input = "http://service/UserManagement/addUserRequest", output = "http://service/UserManagement/addUserResponse")
    public String addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Delete")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://service/", className = "service.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://service/", className = "service.DeleteResponse")
    @Action(input = "http://service/UserManagement/DeleteRequest", output = "http://service/UserManagement/DeleteResponse")
    public String delete(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://service/", className = "service.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://service/", className = "service.GetUserByIdResponse")
    @Action(input = "http://service/UserManagement/getUserByIdRequest", output = "http://service/UserManagement/getUserByIdResponse")
    public User getUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service/", className = "service.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service/", className = "service.GetUserResponse")
    @Action(input = "http://service/UserManagement/getUserRequest", output = "http://service/UserManagement/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<service.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://service/", className = "service.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://service/", className = "service.GetUsersResponse")
    @Action(input = "http://service/UserManagement/getUsersRequest", output = "http://service/UserManagement/getUsersResponse")
    public List<User> getUsers();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Update")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Update", targetNamespace = "http://service/", className = "service.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://service/", className = "service.UpdateResponse")
    @Action(input = "http://service/UserManagement/UpdateRequest", output = "http://service/UserManagement/UpdateResponse")
    public String update(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

}
